### PR TITLE
Adding framework

### PR DESCRIPTION
**Pull request by perezrei**
Hello Sheyla, I'm sending you the wireframe of my proposal for reviewing. Please let me know what do you think

### CODE REVIEW

**Comment by perezrei** [comment]
Feedback to my partner design proposal.

 Layout
 Navegation
 Typography
 Content
 Colour

**Review by sheybusta — APPROVED** [review]
Approve done!

**Comment by sheybusta** [comment]
Well done. I merged to my main. Thanks!

**Review by sheybusta — COMMENTED** [review]
Good code of conduct.

**Comment by perezrei** [comment]
Ok I’m glad you like it

**Pull request merged**
